name: example-basic
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          # The version of Node.js that will be used
          node-version: 18
          
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn install
          yarn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
